// Cultural section-placement helpers — plan §26.
//
// Each helper receives the already-rendered HTML, the content items that belong
// to a specific `section` target, and the full profile for context (e.g.
// subRegion copy, bilingual flags). Every helper is a pure string transform.
//
// Design goals:
//   - No DOM parser dependency — we operate on well-known skeleton anchors.
//   - Graceful degradation: if the expected anchor is missing (e.g. a hero
//     that didn't emit `.hero-names`), content is appended to the hero root or
//     dropped silently rather than crashing.
//   - Values are HTML-escaped unless they're explicit multiline fields
//     (textarea), which are escaped but then allowed to carry line breaks.

import type { CulturalProfile, FieldDefinition } from "@/lib/types";

type ContentItem = CulturalProfile["contentItems"][number];

// ---------- Shared utils ---------------------------------------------------

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function getValue(item: ContentItem, key: string): string | undefined {
  const v = item.values?.[key];
  if (typeof v !== "string") return undefined;
  const trimmed = v.trim();
  if (!trimmed) return undefined;
  return trimmed;
}

function placeholderOf(field: FieldDefinition): string | undefined {
  return field.placeholder && field.placeholder.trim()
    ? field.placeholder.trim()
    : undefined;
}

/** Best-available value for a field: couple input > placeholder > undefined. */
function resolveField(item: ContentItem, field: FieldDefinition): string | undefined {
  const actual = getValue(item, field.key);
  if (actual) return actual;
  return placeholderOf(field);
}

/** Joins non-empty fields of a single item into a single HTML snippet. */
function renderItemAsList(item: ContentItem): string {
  const parts: string[] = [];
  for (const field of item.fields) {
    const value = resolveField(item, field);
    if (!value) continue;
    const label = escapeHtml(field.label);
    const escaped = escapeHtml(value).replace(/\n/g, "<br>");
    if (field.type === "textarea") {
      parts.push(`<p><strong>${label}:</strong> ${escaped}</p>`);
    } else {
      parts.push(`<p><strong>${label}:</strong> ${escaped}</p>`);
    }
  }
  return parts.join("\n");
}

/** Picks the first non-empty field value from an item. */
function firstNonEmptyValue(item: ContentItem): string | undefined {
  for (const field of item.fields) {
    const v = resolveField(item, field);
    if (v) return v;
  }
  return undefined;
}

// ---------- Hero injection -------------------------------------------------
// The hero is generated by Call 3 as a self-contained <section class="hero">.
// Known DOM hooks (§30 element label map):
//   .hero-names      — couple names block
//   .hero-tagline    — supporting line under names
//   .hero-cta        — RSVP button
// We attach cultural content near these hooks by string replacement.

function prependInsideFirstMatch(html: string, pattern: RegExp, snippet: string): string {
  return html.replace(pattern, (match) => `${match}\n${snippet}`);
}

function appendBeforeEnd(html: string, tag: string, snippet: string): string {
  const idx = html.lastIndexOf(`</${tag}>`);
  if (idx === -1) return html + snippet;
  return html.slice(0, idx) + snippet + html.slice(idx);
}

export function injectHeroEyebrow(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  const texts = items
    .map(firstNonEmptyValue)
    .filter((v): v is string => Boolean(v))
    .map((v) => `<p class="hero-eyebrow cultural-hero-eyebrow">${escapeHtml(v)}</p>`);
  if (texts.length === 0) return html;
  const snippet = texts.join("\n");
  // Try to insert directly before the couple names block. If missing, prepend
  // inside the hero section.
  const beforeNames = /<([a-zA-Z0-9]+)[^>]*class="[^"]*hero-names[^"]*"[^>]*>/;
  if (beforeNames.test(html)) {
    return html.replace(beforeNames, (m) => `${snippet}\n${m}`);
  }
  const heroOpen = /<section[^>]*class="[^"]*hero[^"]*"[^>]*>/i;
  if (heroOpen.test(html)) {
    return prependInsideFirstMatch(html, heroOpen, snippet);
  }
  return html;
}

export function injectHeroNamesArea(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  const blocks = items
    .map((item) => {
      const inner = renderItemAsList(item);
      if (!inner) return "";
      return `<div class="hero-family cultural-hero-family">${inner}</div>`;
    })
    .filter(Boolean);
  if (blocks.length === 0) return html;
  const snippet = blocks.join("\n");
  const namesBlock = /(<[^>]*class="[^"]*hero-names[^"]*"[^>]*>[\s\S]*?<\/[^>]+>)/;
  if (namesBlock.test(html)) {
    return html.replace(namesBlock, (m) => `${m}\n${snippet}`);
  }
  return appendBeforeEnd(html, "section", snippet);
}

export function injectHeroDateArea(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  const snippets = items
    .map(firstNonEmptyValue)
    .filter((v): v is string => Boolean(v))
    .map((v) => `<p class="hero-date-note cultural-hero-date">${escapeHtml(v)}</p>`);
  if (snippets.length === 0) return html;
  const snippet = snippets.join("\n");
  const dateBlock = /(<[^>]*class="[^"]*hero-date[^"]*"[^>]*>[\s\S]*?<\/[^>]+>)/;
  if (dateBlock.test(html)) {
    return html.replace(dateBlock, (m) => `${m}\n${snippet}`);
  }
  return appendBeforeEnd(html, "section", snippet);
}

export function injectHeroCtaArea(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  // Per §26, this is the slot used for Chuppah time (Jewish) — must be
  // impossible to miss, so wrap it in a prominent banner class.
  const parts = items
    .map(firstNonEmptyValue)
    .filter((v): v is string => Boolean(v))
    .map(
      (v) =>
        `<p class="hero-cta-note cultural-hero-cta"><strong>${escapeHtml(v)}</strong></p>`
    );
  if (parts.length === 0) return html;
  const snippet = parts.join("\n");
  const ctaAnchor = /(<[^>]*class="[^"]*hero-cta[^"]*"[^>]*>[\s\S]*?<\/[^>]+>)/;
  if (ctaAnchor.test(html)) {
    return html.replace(ctaAnchor, (m) => `${snippet}\n${m}`);
  }
  return appendBeforeEnd(html, "section", snippet);
}

// ---------- FAQ injection --------------------------------------------------

export function injectFAQCulturalItems(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  if (items.length === 0) return html;
  const faqHtml = items
    .map((item) => {
      const answer = renderItemAsList(item);
      if (!answer) return "";
      const question = escapeHtml(item.label);
      return `<div class="faq-item cultural-faq-item reveal">
  <button class="faq-question" type="button">
    <span>${question}</span><span class="faq-icon">+</span>
  </button>
  <div class="faq-answer" style="display:none">${answer}</div>
</div>`;
    })
    .filter(Boolean)
    .join("\n");
  if (!faqHtml) return html;

  // Append inside the .faq-list container if present, else before </section>.
  const faqList = /(<div[^>]*class="[^"]*faq-list[^"]*"[^>]*>)([\s\S]*?)(<\/div>)/;
  const match = faqList.exec(html);
  if (match) {
    return (
      html.slice(0, match.index) +
      match[1] +
      match[2] +
      "\n" +
      faqHtml +
      "\n" +
      match[3] +
      html.slice(match.index + match[0].length)
    );
  }
  return html;
}

// ---------- Footer injection -----------------------------------------------

export function injectFooterCulturalItems(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  if (items.length === 0) return html;
  const blocks = items
    .map((item) => {
      const inner = renderItemAsList(item);
      if (!inner) return "";
      return `<div class="footer-cultural">${inner}</div>`;
    })
    .filter(Boolean)
    .join("\n");
  if (!blocks) return html;
  const idx = html.lastIndexOf("</footer>");
  if (idx === -1) return html + blocks;
  return html.slice(0, idx) + blocks + "\n" + html.slice(idx);
}

// ---------- Custom section injection ---------------------------------------

export function injectCustomCulturalSections(
  html: string,
  items: ContentItem[],
  _profile: CulturalProfile
): string {
  if (items.length === 0) return html;
  const sections = items
    .map((item) => {
      const inner = renderItemAsList(item);
      if (!inner) return "";
      const heading = escapeHtml(item.customSectionLabel ?? item.label);
      return `<section class="custom-section cultural-custom-section">
  <div class="custom-section-inner">
    <h2 class="custom-section-heading">${heading}</h2>
    <div class="custom-section-body">${inner}</div>
  </div>
</section>`;
    })
    .filter(Boolean)
    .join("\n");
  if (!sections) return html;
  const idx = html.indexOf("<footer");
  if (idx === -1) return html + sections;
  return html.slice(0, idx) + sections + "\n" + html.slice(idx);
}
